# Generated by Django 4.2.9 on 2024-03-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0090_alter_resourcebase_polymorphic_ctype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(max_length=255)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.AlterField(
            model_name="hierarchicalkeyword",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name="slug"),
        ),
        migrations.CreateModel(
            name="LocalAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.asset",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Local assets",
            },
            bases=("base.asset",),
        ),
        migrations.AddField(
            model_name="link",
            name="asset",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.asset"),
        ),
    ]
