# Generated by Django 4.2.16 on 2025-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0092_migrate and_remove_resourcebase_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcebase",
            name="custom_md",
            field=models.TextField(
                blank=True, help_text="a custom metadata field", null=True, verbose_name="Custom Md"
            ),
        ),
    ]
