# Generated by Django 4.2.9 on 2024-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0092_generate_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localasset",
            name="location",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
